# Generated by Django 5.0.4 on 2024-05-29 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_hope', '0006_alter_ssoinfo_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssoinfo',
            name='uuid',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
