# Generated by Django 5.0.7 on 2024-09-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_hope', '0008_alter_userprofile_country_alter_userprofile_journey_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useridentityinfo',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='agreed',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='journey',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='registered',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='subscribed_to_30_day_recovery',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='aliveandkicking_waiver_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hobbies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='marital_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ostomy_type',
            field=models.CharField(blank=True, choices=[('Ileostomy', 'Ileostomy'), ('Colostomy', 'Colostomy'), ('Urostomy', 'Urostomy'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='registration_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state_province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscribed_to_aliveandkicking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='surgeon_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='surgery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='surgery_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='team_hope_all_complete',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='team_hope_docusign_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='team_hope_training_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useridentityinfo',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subscribed_to_email_updates',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('Considering Surgery', 'Considering Surgery'), ('Ostomate', 'Ostomate'), ('care', 'Caregiver'), ('Medical Professional', 'Medical Professional'), ('Supporter', 'Supporter'), ('Admin', 'Admin')], default='Supporter', max_length=50),
        ),
    ]
