# Generated by Django 5.0.7 on 2024-09-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_hope', '0011_userprofile_bio_alter_userprofile_marital_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='marital_status',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='relationship_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Dating', 'Dating'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Separated', 'Separated'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
