# Generated by Django 5.0.7 on 2024-09-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_hope', '0012_remove_userprofile_marital_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[('Hispanic or Latino', 'Hispanic or Latino'), ('Not Hispanic or Latino', 'Not Hispanic or Latino'), ('American Indian or Alaska Native', 'American Indian or Alaska Native'), ('Asian', 'Asian'), ('Black or African American', 'Black or African American'), ('Native Hawaiian or Other Pacific Islander', 'Native Hawaiian or Other Pacific Islander'), ('White', 'White'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
