# Generated by Django 5.0.4 on 2024-11-17 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_hope', '0014_remove_userprofile_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='docusign_aliveandkicking_envelope_id',
            field=models.TextField(default='', editable=False),
        ),
    ]
