# Generated by Django 5.0.4 on 2024-12-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_hope', '0015_userprofile_docusign_aliveandkicking_envelope_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='docusign_teamhope_envelope_id',
            field=models.TextField(default='', editable=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscribed_to_teamhope',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='teamhope_member_role',
            field=models.CharField(blank=True, choices=[('Member', 'Member'), ('Volunteer', 'Volunteer')], default='Member', max_length=100, null=True),
        ),
    ]
