# Generated by Django 5.0.4 on 2024-12-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_hope', '0016_userprofile_docusign_teamhope_envelope_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ostomy_type',
            field=models.CharField(blank=True, choices=[('Colostomy', 'Colostomy/Ileostomy'), ('Urostomy', 'Urostomy'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='teamhope_member_role',
            field=models.CharField(blank=True, choices=[('Participant', 'Participant'), ('Volunteer', 'Volunteer')], default='Participant', max_length=100, null=True),
        ),
    ]
