# Generated by Django 5.0.4 on 2025-02-03 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_hope', '0017_alter_userprofile_ostomy_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='teamhope_member_role',
            field=models.CharField(blank=True, choices=[('Participant', 'Participant'), ('Volunteer', 'Volunteer')], max_length=100, null=True),
        ),
    ]
