# Generated by Django 5.0.4 on 2025-02-03 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_hope', '0018_alter_userprofile_teamhope_member_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ostomy_type',
        ),
    ]
