# Generated by Django 5.1.6 on 2025-02-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team_hope", "0019_remove_userprofile_ostomy_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="teamhope_member_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Participant", "I want to Connect with a Veteran Ostimate"),
                    ("Volunteer", "Veteran Ostomate Volunteer"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
