# Generated by Django 5.1.6 on 2025-02-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team_hope", "0020_alter_userprofile_teamhope_member_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="teamhope_member_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Participant", "I want to Connect with a Veteran Ostomate"),
                    ("Volunteer", "Veteran Ostomate Volunteer"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
