# Generated by Django 5.1.6 on 2025-03-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team_hope", "0021_alter_userprofile_teamhope_member_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profilepictures/"
            ),
        ),
    ]
