# Generated by Django 5.1.6 on 2025-03-13 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team_hope", "0022_alter_userprofile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
