# Generated by Django 5.1.6 on 2025-04-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team_hope", "0025_alter_userprofile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="aliveandkicking_waiver_complete",
            field=models.BooleanField(
                default=False, verbose_name="Alive And Kicking Waiver"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="team_hope_docusign_complete",
            field=models.BooleanField(default=False, verbose_name="Team Hope Docusign"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="team_hope_training_complete",
            field=models.BooleanField(default=False, verbose_name="Team Hope Training"),
        ),
    ]
