# Generated by Django 5.1.6 on 2025-05-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "team_hope",
            "0026_alter_userprofile_aliveandkicking_waiver_complete_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="communication_type",
            field=models.TextField(
                blank=True,
                choices=[
                    ("phone", "Phone"),
                    ("email", "Email"),
                    ("chat", "Private Online Chat"),
                ],
                default="email",
                verbose_name="Preferred method of Communication",
            ),
        ),
    ]
