# Generated by Django 5.1.6 on 2025-05-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team_hope", "0029_alter_usermethodofcommunication_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
