# Generated by Django 5.1.6 on 2025-06-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team_hope", "0030_userprofile_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
