# Generated by Django 5.1.6 on 2025-06-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team_hope", "0031_userprofile_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="signup_complete",
            field=models.BooleanField(default=False),
        ),
    ]
