# Generated by Django 5.1.6 on 2025-07-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team_hope", "0032_userprofile_signup_complete"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="registered_ak",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="registered_th",
            field=models.BooleanField(default=False),
        ),
    ]
