# Generated by Django 5.1.6 on 2026-03-10 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team_hope", "0033_userprofile_registered_ak_userprofile_registered_th"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermethodofcommunication",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="communications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
