# Generated by Django 5.1.6 on 2026-03-10 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("team_hope", "0035_usermethodofcommunication_profile_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermethodofcommunication",
            name="profile",
        ),
    ]
