services:
  postgres:
    image: postgres:14
    restart: always
    #name the container
    container_name: postgres-th
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'TeamHope1'
    ports:
      - "5431:5432"
    expose:
      - "5431"
    volumes:
      - ./data:/var/lib/postgresql/data
  redis:
    image: redis:6
    restart: always
    container_name: redis-th
    ports:
      - "6379:6379"